#!/usr/bin/env python3
"""Assemble a ready-to-paste validation prompt with the three research docs embedded inline.

Reads the template at prompts/validation_prompt.md, keeps the reviewer instructions
(everything from the '## PROMPT' heading onward), and replaces the three document
placeholders with the current contents of the docs. Output is written to
prompts/validation_prompt.FILLED.md (git-ignored; regenerate instead of editing).

Run:  python3 scripts/build_validation_prompt.py
"""
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parents[1]
TEMPLATE = REPO / "prompts" / "validation_prompt.md"
OUT = REPO / "prompts" / "validation_prompt.FILLED.md"

# placeholder filename -> source doc
DOCS = {
    "reddit_gamma_strategy_terms.md": REPO / "docs" / "reddit_gamma_strategy_terms.md",
    "data_provider_assessment.md": REPO / "docs" / "data_provider_assessment.md",
    "phase_1_plan.md": REPO / "docs" / "phase_1_plan.md",
}

HEADER = (
    "# GammaEdge Research: Filled Validation Prompt (auto-generated)\n\n"
    "Paste this entire file into an independent model (GPT, Gemini, a fresh Claude).\n"
    "Generated by scripts/build_validation_prompt.py. Do not edit by hand; re-run the script.\n\n"
    "---\n\n"
)


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def main() -> None:
    if not TEMPLATE.exists():
        die(f"template not found: {TEMPLATE}")
    lines = TEMPLATE.read_text(encoding="utf-8").splitlines()

    # Keep only the reviewer instructions: from the '## PROMPT' heading onward.
    start = next((i for i, ln in enumerate(lines) if ln.startswith("## PROMPT")), None)
    if start is None:
        die("could not find '## PROMPT' heading in template")
    body = "\n".join(lines[start + 1:]).strip("\n")

    # Embed each document in place of its placeholder line.
    for fname, path in DOCS.items():
        if not path.exists():
            die(f"doc not found: {path}")
        placeholder = f"<<replace this line with the full contents of {fname}>>"
        if placeholder not in body:
            die(f"placeholder not found for {fname}: {placeholder!r}")
        content = path.read_text(encoding="utf-8").strip("\n")
        block = f"----- BEGIN {fname} -----\n\n{content}\n\n----- END {fname} -----"
        body = body.replace(placeholder, block)

    # Sanity check: no placeholders should survive.
    if "<<replace this line" in body:
        die("a placeholder was left unfilled after substitution")

    OUT.write_text(HEADER + body + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
