#!/usr/bin/env python3
"""Assemble a ready-to-paste code+model review prompt with the full source embedded.

Reads prompts/code_review_prompt.md, keeps the reviewer instructions (everything
from the '## PROMPT' heading onward), and replaces the source placeholder with the
current contents of the repo's code, tests, docs, and config. Output is written to
prompts/code_review_prompt.FILLED.md (git-ignored; regenerate instead of editing).

Run:  python3 scripts/build_code_review_prompt.py
"""
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parents[1]
TEMPLATE = REPO / "prompts" / "code_review_prompt.md"
OUT = REPO / "prompts" / "code_review_prompt.FILLED.md"
PLACEHOLDER = "<<replace this line with the embedded source tree via scripts/build_code_review_prompt.py>>"

# Directories walked for source, and the file extensions embedded from them.
# scripts/ is intentionally excluded: it is only prompt-builder tooling, and its
# source contains the placeholder string, which would trip the unfilled-guard.
INCLUDE_DIRS = ["src", "tests", "config", "docs", ".github/workflows"]
INCLUDE_EXTS = {".py", ".toml", ".md", ".yml", ".yaml", ".json", ".cfg", ".ini"}
# Individual top-level files worth including.
INCLUDE_FILES = ["README.md", "HANDOFF.md", "requirements.txt", "requirements.lock.txt", ".gitignore"]
# Never embed these (noise / generated / self).
SKIP_NAMES = {"code_review_prompt.FILLED.md", "validation_prompt.FILLED.md"}
SKIP_PARTS = {"__pycache__", ".venv", ".git"}

HEADER = (
    "# GammaEdge Research: Filled Code & Model Review Prompt (auto-generated)\n\n"
    "Paste this entire file into an independent, comparable model. Generated by\n"
    "scripts/build_code_review_prompt.py. Do not edit by hand; re-run the script.\n\n"
    "---\n\n"
)


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def _wanted(path: Path) -> bool:
    if path.name in SKIP_NAMES:
        return False
    if any(part in SKIP_PARTS for part in path.parts):
        return False
    return path.suffix in INCLUDE_EXTS


def collect_files() -> list[Path]:
    found: list[Path] = []
    for rel in INCLUDE_DIRS:
        base = REPO / rel
        if base.is_dir():
            found += [p for p in base.rglob("*") if p.is_file() and _wanted(p)]
    for name in INCLUDE_FILES:
        p = REPO / name
        if p.is_file():
            found.append(p)
    # Stable, readable order.
    return sorted(set(found), key=lambda p: str(p.relative_to(REPO)))


def render_tree(files: list[Path]) -> str:
    listing = "\n".join(str(p.relative_to(REPO)) for p in files)
    blocks = [f"## Embedded source ({len(files)} files)\n\n```\n{listing}\n```\n"]
    for p in files:
        rel = p.relative_to(REPO)
        text = p.read_text(encoding="utf-8", errors="replace").rstrip("\n")
        blocks.append(f"----- BEGIN {rel} -----\n\n{text}\n\n----- END {rel} -----\n")
    return "\n".join(blocks)


def main() -> None:
    if not TEMPLATE.exists():
        die(f"template not found: {TEMPLATE}")
    lines = TEMPLATE.read_text(encoding="utf-8").splitlines()

    start = next((i for i, ln in enumerate(lines) if ln.startswith("## PROMPT")), None)
    if start is None:
        die("could not find '## PROMPT' heading in template")
    body = "\n".join(lines[start + 1:]).strip("\n")

    if PLACEHOLDER not in body:
        die(f"placeholder not found: {PLACEHOLDER!r}")

    files = collect_files()
    if not files:
        die("no source files collected; check INCLUDE_DIRS")
    body = body.replace(PLACEHOLDER, render_tree(files))

    if "<<replace this line" in body:
        die("a placeholder was left unfilled after substitution")

    OUT.write_text(HEADER + body + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size:,} bytes, {len(files)} files embedded)")


if __name__ == "__main__":
    main()
